# Generated by Django 6.0.7 on 2026-07-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_channel_item_name_remove_item_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='channel',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
