# Generated by Django 6.0.7 on 2026-08-06 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_name_item_title_item_channel_item_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('rol', models.CharField(choices=[('mijoz', 'Mijoz'), ('usta', 'Usta'), ('admin', 'Admin')], default='mijoz', max_length=20)),
                ('viloyat', models.CharField(max_length=100)),
                ('shahar', models.CharField(max_length=100)),
                ('haqida', models.TextField(blank=True)),
                ('tajriba', models.IntegerField(default=0)),
                ('kategoriya', models.CharField(blank=True, max_length=100)),
                ('konikma', models.TextField(blank=True)),
                ('vaqt', models.CharField(blank=True, max_length=50)),
                ('narx', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='portfolio/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='frontend.profile')),
            ],
        ),
    ]
