# Generated by Django 6.0.7 on 2026-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_profile_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shahar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viloyat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
