# Generated by Django 6.0.7 on 2026-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_profile_shahar_alter_profile_telefon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usta_id', models.IntegerField()),
                ('xizmat_turi', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('manzil', models.CharField(max_length=255)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
