# Generated by Django 6.0.5 on 2026-08-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_buyurtma_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='usta_id',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='usta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usta_buyurtmalari', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
