# Generated by Django 6.0.6 on 2026-08-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_remove_buyurtma_usta_id_buyurtma_usta'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='manzil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='sana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='vaqt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
